pihole:
  container_name: pihole
  image: pihole/pihole:2023.03.1
  ports:
    - 53:53/tcp
    - 53:53/udp
    - 67:67/udp
  expose:
    - "80"
  dns:
    - 127.0.0.1
  environment:
    TZ: 'America/New_York'
    VIRTUAL_HOST: pihole.local
    FTLCONF_REPLY_ADDR4: {{ ansible_default_ipv4.address }}
    FTLCONF_MAXDBDAYS: 60
    FTLCONF_BLOCK_ICLOUD_PR: "true"
    DNSMASQ_LISTENING: "all"
  ulimits:
    nofile:
      soft: 1024
      hard: 4096
  networks:
    - default
  volumes:
    - pihole-data:/etc/pihole/
  labels:
    - docker-volume-backup.stop-during-backup=true
