postgres:
  image: postgres:16
  container_name: postgres
  volumes:
    - postgres-data:/var/lib/postgresql/data
    - ./postgres/init-scripts:/docker-entrypoint-initdb.d
  expose:
    - "9090"
  environment:
    - TZ=America/New_York
    - POSTGRES_USER={{ ansible_ssh_user }}
    - POSTGRES_PASSWORD={{ postgres_password }}
    - POSTGRES_HOST_AUTH_METHOD=scram-sha-256
    - POSTGRES_INITDB_ARGS=--auth-host=scram-sha-256
  labels:
    - docker-volume-backup.stop-during-backup=true
  healthcheck:
    test: ["CMD-SHELL", "pg_isready"]
