---
- block:
  - name: Create configuration directory
    file:
      path: "{{ compose_project_dir }}/vmagent"
      state: directory
      mode: 0755

  - name: Add Prometheus-compatible scrape config
    copy:
      src: ./templates/prometheus.yml
      dest: "{{ compose_project_dir }}/vmagent/prometheus.yml"
      mode: "0644"
    notify: Restart vmagent
  tags: vmagent
