docker-state-exporter:
  image: karugaru/docker_state_exporter
  container_name: docker-state-exporter
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  expose:
    - 8080
  healthcheck:
    test: [ "CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:8080/metrics || exit 1" ]

