mqtt:
 # The MQTT broker to connect to
 server: tcp://mosquitto:1883
 topic_path: zigbee2mqtt/+
metrics:
 # The name of the metric in prometheus
 - prom_name: temperature
  # The name of the metric in a MQTT JSON message
   mqtt_name: temperature
  # The prometheus type for this metric. Valid values are: "gauge" and "counter"
   type: gauge
 - prom_name: humidity
  # The name of the metric in a MQTT JSON message
   mqtt_name: humidity
  # The scale of the metric in a MQTT JSON message (prom_value = mqtt_value * scale)
   mqtt_value_scale: 1
  # The prometheus type for this metric. Valid values are: "gauge" and "counter"
   type: gauge
