---
- name: Restart homebridge process
  community.docker.docker_container_exec:
    container: homebridge
    command: pkill -15 homebridge

- name: Restart homebridge container
  community.docker.docker_compose_v2:
    project_src: "{{ compose_project_dir }}"
    services: homebridge
    state: restarted
