- name: apply base configuration
  hosts: all
  roles:
    - base

- name: install and configure docker
  hosts: all
  roles:
    - docker

- name: configure docker containers using compose
  hosts: all
  roles:
    - compose
