---
- name: First run - insecure ssh to default user account
  hosts: all
  vars_files: vars.yml
  gather_facts: false
  tags: always
  roles:
    - first_run

- name: Apply base configuration
  hosts: all
  vars_files: vars.yml
  gather_facts: false
  roles:
    - base

- name: Install node
  hosts: all
  gather_facts: false
  roles:
    - node
  vars:
    nodejs_major_version: 18

- name: Install and configure docker
  hosts: all
  vars_files: vars.yml
  gather_facts: false
  roles:
    - docker

- name: Configure docker containers using compose
  hosts: all
  vars_files: vars.yml
  gather_facts: false
  roles:
    - compose

- name: Set up a VNC server that boots XFCE
  hosts: all
  vars_files: vars.yml
  gather_facts: false
  roles:
    - vnc

- name: Set up a Samba server to share mounted drives
  hosts: all
  vars_files: vars.yml
  gather_facts: false
  roles:
    - samba

- name: Install a backup restoration script
  hosts: all
  vars_files: vars.yml
  gather_facts: false
  roles:
    - restore
