---
- name: First run - insecure ssh to default user account
  hosts: all
  vars_files: vars.yml
  gather_facts: false
  tags: always
  roles:
    - first_run

- name: Apply base configuration
  hosts: all
  vars_files: vars.yml
  gather_facts: false
  roles:
    - base

- name: Install and configure docker
  hosts: all
  vars_files: vars.yml
  gather_facts: false
  roles:
    - docker

- name: Configure docker containers using compose
  hosts: all
  vars_files: vars.yml
  gather_facts: false
  roles:
    - compose
