- name: add Vault secrets
  include_vars: "{{ playbook_dir }}/secrets.yml"
  tags: always

- name: install docker-compose
  become: yes
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - docker-compose-plugin

- name: get current docker volumes
  command: "docker volume ls --format='{% raw %}{{.Name}}{% endraw %}'" # noqa var-spacing
  register: current_volumes
  changed_when: no

- name: get requested persistent volumes in compose file
  set_fact:
    requested_volumes: "{{ lookup('template', './docker-compose.yml') | from_yaml | json_query('volumes') | list }}"

# TODO: this will try to recreate ALL volumes, not just `external: true` ones
- name: create volumes if they don't exist
  command: docker volume create {{ item }}
  loop: "{{ requested_volumes | difference(current_volumes.stdout.split('\n')) }}"
  register: vol_create
  changed_when: vol_create.stdout == item

- name: template docker-compose.yml to ~/
  template:
    src: ./templates/docker-compose.yml
    dest: /home/{{ ansible_facts['user_id'] }}/docker-compose.yml
    mode: 0644

- name: add Caddyfile
  copy:
    src: ./templates/Caddyfile
    dest: /home/{{ ansible_facts['user_id'] }}/Caddyfile
    mode: 0644
  notify: caddy-restart

- name: add homebridge config
  template:
    src: ./templates/homebridge-config.json
    dest: /home/{{ ansible_facts['user_id'] }}/homebridge-config.json
    mode: 0644
  notify: homebridge-restart

- name: start services using Compose
  community.docker.docker_compose:
    project_src: /home/{{ ansible_facts['user_id'] }}
    state: present

- name: inspect ca-certs for Caddy root
  find:
    paths: /etc/ssl/certs
    patterns: caddy-root.pem
    recurse: no
    file_type: any
  register: found_roots

- include_tasks: caddy-root.yml
  when: found_roots.files | length == 0
