watchtower:
  image: containrrr/watchtower
  container_name: watchtower
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  command: --http-api-update --http-api-periodic-polls
  expose:
    - "8080"
  environment:
    - WATCHTOWER_CLEANUP=true
    - WATCHTOWER_POLL_INTERVAL=86400
    - WATCHTOWER_HTTP_API_TOKEN={{watchtower_http_api_token}}
