- name: add Caddyfile
  copy:
    src: ./templates/Caddyfile
    dest: "{{ compose_project_dir }}/Caddyfile"
    mode: 0644
  notify: caddy-restart

- name: inspect ca-certs for Caddy root
  find:
    paths: /etc/ssl/certs
    patterns: caddy-root.pem
    recurse: no
    file_type: any
  register: found_roots

- include_tasks: caddy-root.yml
  when: found_roots.files | length == 0
