---
- name: Add Caddyfile
  copy:
    src: ./templates/Caddyfile
    dest: "{{ compose_project_dir }}/Caddyfile"
    mode: "0644"
  notify: Restart caddy

- name: Inspect ca-certs for Caddy root
  find:
    paths: /etc/ssl/certs
    patterns: caddy-root.pem
    recurse: false
    file_type: any
  register: found_roots

- name: Accept Caddy root CAs
  include_tasks: caddy-root.yml
  when: found_roots.files | length == 0
