---
- name: Reboot
  become: true
  ansible.builtin.reboot:
    reboot_command: shutdown -r now

- name: Reconnect WiFi
  become: true
  ansible.builtin.command: wpa_cli -i wlan0 reconfigure

- name: Restart ssh service
  become: true
  service:
    name: sshd
    state: restarted

- name: Update grub
  become: true
  command: update-grub2
