---
- name: Reboot
  become: true
  ansible.builtin.reboot:
    reboot_command: shutdown -r now

- name: Restart ssh service
  become: true
  service:
    name: sshd
    state: restarted

- name: Update grub
  become: true
  command: update-grub2

- name: Update apt-cache
  become: true
  apt:
    update_cache: true
