---
- name: reboot
  become: true
  reboot:
    reboot_command: shutdown -r now

- name: logout
  meta: reset_connection

- name: wifi-reconnect
  become: true
  command: wpa_cli -i wlan0 reconfigure

- name: restart-ssh-service
  become: true
  service:
    name: sshd
    state: restarted

- name: update grub
  become: true
  command: update-grub2
