---
- name: Reboot
  become: true
  ansible.builtin.reboot:
    reboot_command: shutdown -r now

- name: Restart ssh service
  become: true
  service:
    name: sshd
    state: restarted

- name: Restart NetworkManager service
  become: true
  service:
    name: NetworkManager
    enabled: true
    state: restarted

- name: Update apt-cache
  become: true
  apt:
    update_cache: true

- name: Kill tmux sessions
  ansible.builtin.command:
    cmd: tmux kill-server

- name: Fetch tmux plugins
  ansible.builtin.command:
    cmd: /home/{{ ansible_ssh_user }}/.tmux/plugins/tpm/scripts/install_plugins.sh
