playwright:
  container_name: playwright
  image: browserless/chrome
  expose:
    - "3000"
  environment:
    - SCREEN_WIDTH=1920
    - SCREEN_HEIGHT=1024
    - SCREEN_DEPTH=16
    - ENABLE_DEBUGGER=false
    - PREBOOT_CHROME=true
    - KEEP_ALIVE=true
    - EXIT_ON_HEALTH_FAILURE=true
    - CONNECTION_TIMEOUT=500000
    - MAX_CONCURRENT_SESSIONS=5
    - CHROME_REFRESH_TIME=600000
    - DEFAULT_BLOCK_ADS=false
    - DEFAULT_STEALTH=true
