plex:
  container_name: plex
  image: plexinc/pms-docker
  ports:
    - 32400:32400/tcp
    - 3005:3005/tcp
    - 8324:8324/tcp
    - 32469:32469/tcp
    - 1900:1900/udp
    - 32410:32410/udp
    - 32412:32412/udp
    - 32413:32413/udp
    - 32414:32414/udp
  environment:
    - PLEX_GID={{ ansible_facts['user_gid'] }}
    - PLEX_UID={{ ansible_facts['user_uid'] }}
    - CHANGE_CONFIG_DIR_OWNERSHIP=false
    - TZ=America/New_York
    - ADVERTISE_IP=http://{{ ansible_host }}:32400/
    - ALLOWED_NETWORKS=192.168.1.0/24
    - PLEX_CLAIM="claim-u6b5gTx3BwtztHDFssYx"
  volumes:
    - plex-data:/config
    - /mnt/hdd/media:/media
  devices:
    - /dev/dri:/dev/dri
