---
- block:
  - name: Create configuration directory
    become: true
    file:
      path: "{{ compose_project_dir }}/ddns-route53"
      state: directory
      owner: "{{ ansible_ssh_user }}"
      group: "{{ ansible_ssh_user }}"
      mode: 0755

  - name: Determine services that need to have ddns-route53 authentication config
    ansible.builtin.set_fact:
      ddns_services: "{{ compose_services | selectattr('proxy', 'defined') | selectattr('internet', 'true') }}"

  - name: Copy ddns-route53 config to configuration directory
    template:
      src: ./templates/config.yml.j2
      dest: "{{ compose_project_dir }}/ddns-route53/config.yml"
      mode: "0644"
    notify: Restart ddns-route53

  tags: ddns-route53

