version: "2.2"
networks:
  default:
volumes:
  caddy-data:
    external: true
  homebridge-data:
    external: true
  pihole-data:
    external: true
  vmagent-data:
    external: true
services:
  homebridge:
    container_name: homebridge
    image: oznu/homebridge:2023-01-08
    restart: always
    network_mode: host
    cpu_percent: 75
    logging: &logging
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
    environment:
      - TZ=America/New_York
      - PGID={{ ansible_facts['user_gid'] }}
      - PUID={{ ansible_facts['user_uid'] }}
    volumes:
      - homebridge-data:/homebridge
      - ./homebridge-config.json:/homebridge/config.json
      - ./package.json:/homebridge/package.json
    labels:
      - docker-volume-backup.stop-during-backup=true
  caddy:
    container_name: caddy
    image: caddy:2.4.6-alpine
    restart: always
    logging: *logging
    networks:
      - default
    ports:
      - 443:443/tcp
      - 80:80/tcp
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy-data:/data
  pihole:
    container_name: pihole
    image: pihole/pihole:2023.03.1
    restart: always
    logging: *logging
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 67:67/udp
    expose:
      - "80"
    dns:
      - 127.0.0.1
    environment:
      TZ: 'America/New_York'
      WEBPASSWORD: {{ pihole_admin_pass }}
      VIRTUAL_HOST: pihole.local
      FTLCONF_REPLY_ADDR4: {{ ansible_default_ipv4.address }}
      FTLCONF_MAXDBDAYS: 60
      FTLCONF_BLOCK_ICLOUD_PR: "true"
    ulimits:
      nofile:
        soft: 1024
        hard: 4096
    networks:
      - default
    volumes:
      - pihole-data:/etc/pihole/
    labels:
      - docker-volume-backup.stop-during-backup=true
  pihole-exporter:
    container_name: pihole-exporter
    image: ekofr/pihole-exporter:v0.4.0
    restart: always
    logging: *logging
    environment:
      - PIHOLE_HOSTNAME=pihole
      - PIHOLE_PASSWORD={{ pihole_admin_pass }}
      - PORT=9617
    expose:
      - "9617"
    links:
      - pihole
  unifi-poller:
    container_name: unifi-poller
    image: ghcr.io/unpoller/unpoller:v2.7.12
    logging: *logging
    restart: always
    environment:
      - UP_UNIFI_DEFAULT_URL=https://192.168.1.1
      - UP_UNIFI_DEFAULT_PASS={{unifi_poller_pass}}
      - UP_INFLUXDB_DISABLE=true
    expose:
      - "9130"
  vmagent:
    container_name: vmagent
    image: victoriametrics/vmagent:v1.90.0
    logging: *logging
    restart: always
    expose:
      - "8429"
    volumes:
      - vmagent-data:/vmagentdata
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--promscrape.config=/etc/prometheus/prometheus.yml"
      - "--remoteWrite.url=https://912271:{{ grafana_cloud_api_key }}@prometheus-us-central1.grafana.net/api/prom/push"
  cadvisor:
    container_name: cadvisor
    image: gcr.io/cadvisor/cadvisor:v0.47.0
    restart: always
    devices:
      - "/dev/kmsg:/dev/kmsg"
    expose:
      - "8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
      - /var/run/docker.sock:/var/run/docker.sock:rw
    command:
      - '--housekeeping_interval=55s'
      - '--enable_metrics=cpu,memory,network'
      - '--docker_only=true'
  node-exporter:
    container_name: node-exporter
    image: prom/node-exporter:v1.5.0
    restart: always
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    expose:
      - 9100
  backup:
    container_name: backup
    image: offen/docker-volume-backup
    restart: always
    environment:
      AWS_S3_BUCKET_NAME: rpi-volume-backup
      AWS_ACCESS_KEY_ID: {{ aws_access_key_id }}
      AWS_SECRET_ACCESS_KEY: {{ aws_secret_access_key }}
      BACKUP_RETENTION_DAYS: 14
      NOTIFICATION_URLS: slack://{{slack_token}}@C32FHM7CK
      # TZ on homelab is set to GMT and should stay that way
      BACKUP_CRON_EXPRESSION: 0 7 * * * # 7 am GMT is 2 am EST
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - homebridge-data:/backup/homebridge-data:ro
      - pihole-data:/backup/pihole-data:ro
