ntfy:
  image: binwiederhier/ntfy
  container_name: ntfy
  command:
    - serve
  environment:
    - TZ=America/New_York
  volumes:
    - ./ntfy:/etc/ntfy
    - ntfy-data:/var/cache/ntfy
    - ntfy-users:/var/lib/ntfy
  expose:
    - 80
    - 9090
  healthcheck:
    test: [ "CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost/v1/health || exit 1" ]

