---
- block:
  - name: Add homebridge config
    ansible.builtin.template:
      src: ./templates/homebridge-config.json
      dest: "{{ compose_project_dir }}/homebridge-config.json"
      mode: "0644"
    notify: Restart homebridge

  - name: Add homebridge plugins
    ansible.builtin.copy:
      src: ./templates/package.json
      dest: "{{ compose_project_dir }}/package.json"
      mode: "0644"
    notify:
      - Install plugins
      - Restart homebridge
  tags: homebridge
