---
- name: Enumerate control node ssh keys
  delegate_to: localhost
  stat:
    path: ~/.ssh/id_{{ item }}
  register: key_stats
  loop:
    - ed25519
    - rsa

- name: Choose best ssh key
  ansible.builtin.set_fact:
    control_node_sshkey: "{{ key_stats.results | selectattr('stat.exists', 'equalto', true) | map(attribute='stat.path') | first }}"

- name: Configure the root password from vaulted vars
  ansible.builtin.set_fact:
    ansible_become_pass: "{{ desired_password }}"

- name: Use this ssh key for future auth
  ansible.builtin.set_fact:
    ansible_ssh_private_key_file: "{{ control_node_sshkey }}"
  notify:
    - Logout
