- name: If no connection, change user_name
  set_fact:
    ansible_ssh_user: "{{ ansible_user_first_run }}"
    # it may be necessary to set ansible_ssh_pass here too, if the machine wants password ssh after a fresh install

- name: create '{{ desired_new_user }}' sudo user
  become: true
  user:
    name: "{{ desired_new_user }}"
    password: "{{ ansible_become_pass | string | password_hash('sha256', 'salt', rounds=1000) }}"
    append: yes
    shell: /bin/bash
    groups:
      - sudo
