- name: enumerate control node ssh keys
  local_action:
    module: stat
    path: "~/.ssh/id_{{item}}"
  register: key_stats
  loop:
    - ed25519
    - ecdsa
    - dsa
    - rsa

- name: choose best ssh key
  set_fact:
    control_node_sshkey: "{{ key_stats.results  | selectattr('stat.exists', 'equalto', true) | map(attribute='stat') | map(attribute='path') | first }}"

- name: use this ssh key for future auth
  set_fact:
    ansible_ssh_private_key_file: "{{ control_node_sshkey }}"
  notify:
    - logout
