node-red:
  container_name: node-red
  image: nodered/node-red
  volumes:
    - nodered-data:/data
    - ./node-red/settings.js:/data/settings.js
  environment:
    - TZ=America/New_York
    - PGID={{ ansible_facts['user_gid'] }}
    - PUID={{ ansible_facts['user_uid'] }}
  expose:
    - 1880
