caddy:
  container_name: caddy
  image: caddy
  networks:
    - default
  ports:
    - 443:443/tcp
    - 80:80/tcp
  extra_hosts:
    - host.docker.internal:host-gateway
  volumes:
    - ./caddy/Caddyfile:/etc/caddy/Caddyfile
    - caddy-data:/data
  healthcheck:
    test: [ "CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost/health || exit 1" ]
