caddy:
  container_name: caddy
  image: caddy:2.6.4-alpine
  networks:
    - default
  ports:
    - 443:443/tcp
    - 80:80/tcp
  extra_hosts:
    - host.docker.internal:host-gateway
  volumes:
    - ./caddy/Caddyfile:/etc/caddy/Caddyfile
    - caddy-data:/data
