---
- block:
  - name: Get ZigBee radio device name
    ansible.builtin.shell:
      cmd: ls -l /dev/serial/by-id | grep Sonoff_Zigbee | awk '{print $9}'
    register: device_id

  - name: Create configuration directory
    file:
      path: "{{ compose_project_dir }}/zigbee2mqtt"
      state: directory
      mode: 0755

  - name: Add z2m configuration file
    copy:
      src: ./templates/configuration.yml
      dest: "{{ compose_project_dir }}/zigbee2mqtt/configuration.yml"
      mode: "0644"
    notify: Restart zigbee2mqtt
  tags: zigbee2mqtt
