---
- block:
  - name: Create configuration directories
    file:
      path: "{{ compose_project_dir }}/loki"
      owner: "{{ ansible_ssh_user }}"
      group: "{{ ansible_ssh_user }}"
      state: directory
      mode: 0755

  - name: Add config file
    copy:
      src: ./templates/config.yml
      dest: "{{ compose_project_dir }}/loki/config.yml"
      mode: "0644"
    notify: Restart loki

  tags: loki
