---
- block:
  - name: Create configuration directory
    become: true
    file:
      path: "{{ compose_project_dir }}/authelia"
      state: directory
      owner: "{{ ansible_ssh_user }}"
      group: "{{ ansible_ssh_user }}"
      mode: 0755

  - name: Determine services that need to have Authelia authentication config
    ansible.builtin.set_fact:
      authed_proxies: "{{ compose_services | selectattr('http', 'defined') }}"

  - name: Copy Authelia config to configuration directory
    template:
      src: ./templates/configuration.yml.j2
      dest: "{{ compose_project_dir }}/authelia/configuration.yml"
      mode: "0644"
    notify: Restart authelia

  - name: Template the users database
    template:
      src: ./templates/users_database.yml
      dest: "{{ compose_project_dir }}/authelia/users_database.yml"
      mode: "0644"

  tags: authelia

