redis:
  image: redis:alpine
  container_name: redis
  volumes:
    - redis-data:/data
  expose:
    - "6379"
  environment:
    - TZ=America/New_York
  healthcheck:
    test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
