---
- name: Gather facts
  setup:

- name: Install packages
  become: true
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  loop:
    - tightvncserver
    - dbus-x11

- name: Create .vnc directory
  ansible.builtin.file:
    path: /home/{{ ansible_ssh_user }}/.vnc
    state: directory
    mode: 0755

- name: Configure a VNC password
  ansible.builtin.shell:
    cmd: |
      set -o pipefail #
      echo '{{ vnc_password }}' | vncpasswd -f > /home/{{ ansible_ssh_user }}/.vnc/passwd
    executable: /bin/bash
    creates: /home/{{ ansible_ssh_user }}/.vnc/passwd

- name: Set correct permissions for VNC passwd file
  ansible.builtin.file:
    path: /home/{{ ansible_ssh_user }}/.vnc/passwd
    mode: 0600

- name: Create VNC configuration file
  ansible.builtin.copy:
    src: ./templates/xstartup
    dest: /home/{{ ansible_ssh_user }}/.vnc/xstartup
    mode: "755"

- name: Create a VNC systemd service
  become: true
  ansible.builtin.template:
    src: ./templates/vncserver@.service
    dest: /etc/systemd/system/vncserver@.service
  notify: Reload systemctl daemon

- name: Start/enable VNC systemd service
  become: true
  service:
    name: vncserver@1.service
    enabled: true
    state: started
