mosquitto:
  container_name: mosquitto
  image: eclipse-mosquitto
  expose:
    - 1883
    - 9001
  volumes:
    - mosquitto-data:/mosquitto/data
    - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
