mosquitto:
  container_name: mosquitto
  image: eclipse-mosquitto
  expose:
    - 1883
    - 9001
  volumes:
    - mosquitto-data:/mosquitto/data
    - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
  healthcheck:
    test: ["CMD-SHELL", "mosquitto_sub -h localhost -p 1883 -t '#' -C 1 | grep online || exit 1"]
