homeassistant: false
permit_join: true
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://mosquitto
serial:
  port: /dev/ttyACM0
frontend:
  url: https://zigbee2mqtt.{{ internet_domain }}
advanced:
  log_output:
    - console
  last_seen: ISO_8601
devices:
  '0x00158d0009ef8646':
    friendly_name: Bedroom
  '0xb0ce18140001ce00':
    friendly_name: 'Living Room Table Lamp'
  '0xb0ce181400080417':
    friendly_name: 'Living Room Left Standing Lamp'
  '0x00158d008b043fef':
    friendly_name: Basement
  '0xb0ce181400051198':
    friendly_name: 'Living Room Right Standing Lamp'
