---
- name: Refresh pihole-FTL
  community.docker.docker_container_exec:
    container: pihole
    command: pihole restartdns reload-lists && sudo service pihole-FTL restart

- name: Reload gravity
  community.docker.docker_container_exec:
    container: pihole
    command: pihole -g
