- name: Gather facts
  setup:

- name: Get arch from dpkg
  command: dpkg --print-architecture
  register: dpkg_arch
  changed_when: false

- name: Install nodejs prerequisites
  become: true
  apt:
    name:
      - gcc
      - g++
      - make
    state: present

- name: Add nodejs repository
  become: true
  ansible.builtin.deb822_repository:
    name: nodesource
    types: deb
    uris: https://deb.nodesource.com/node_{{ nodejs_major_version }}.x
    suites: "{{ ansible_facts['lsb'].codename }}"
    components: main
    architectures: "{{ dpkg_arch.stdout }}"
    signed_by: https://deb.nodesource.com/gpgkey/nodesource.gpg.key

- name: Install nodejs
  become: true
  apt:
    name: nodejs
    state: present
