backup:
  container_name: backup
  image: offen/docker-volume-backup
  environment:
    AWS_S3_BUCKET_NAME: {{ backups_bucket_name }}
    AWS_ACCESS_KEY_ID: {{ backups_aws_access_key_id }}
    AWS_SECRET_ACCESS_KEY: {{ backups_aws_secret_access_key }}
    BACKUP_RETENTION_DAYS: 14
    NOTIFICATION_URLS: slack://{{slack_token}}@C32FHM7CK
    # TZ on homelab is set to GMT and should stay that way
    BACKUP_CRON_EXPRESSION: 0 7 * * * # 7 am GMT is 2 am EST
    BACKUP_EXCLUDE_REGEXP: ".*/(Cache|Metadata|node_modules|pihole-FTL.db)/.*"
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock:ro
    - homebridge-data:/backup/homebridge-data:ro
    - pihole-data:/backup/pihole-data:ro
    - changedetection-data:/backup/changedetection-data:ro
    - grafana-data:/backup/grafana-data:ro
    - nodered-data:/backup/nodered-data:ro
    - plex-data:/backup/plex-data:ro
    - postgres-data:/backup/postgres-data:ro
    - zigbee2mqtt-data:/backup/zigbee2mqtt-data:ro
