---
- block:
  - name: Create configuration directory
    file:
      path: "{{ compose_project_dir }}/mosquitto"
      state: directory
      mode: 0755

  - name: Add Mosquitto conf file
    copy:
      src: ./templates/mosquitto.conf
      dest: "{{ compose_project_dir }}/mosquitto/mosquitto.conf"
      mode: "0644"
    notify: Restart mosquitto
  tags: mosquitto
