changedetection:
  image: ghcr.io/dgtlmoon/changedetection.io
  container_name: changedetection
  volumes:
    - changedetection-data:/datastore
  expose:
    - "5000"
  environment:
    - PGID={{ ansible_facts['user_gid'] }}
    - PUID={{ ansible_facts['user_uid'] }}
    - PLAYWRIGHT_DRIVER_URL=ws://playwright:3000/?stealth=1&--disable-web-security=true
    - BASE_URL=https://changedetection.homelab.local
  depends_on:
    playwright:
      condition: service_started
