loki:
  image: grafana/loki:2.9.7
  container_name: loki
  command: "-config.file=/etc/loki/config.yml -target=all"
  expose:
    - 3100
    - 7946
    - 9095
  ports:
    - 3100:3100
  volumes:
    - ./loki/config.yml:/etc/loki/config.yml
  healthcheck:
    test: [ "CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:3100/ready || exit 1" ]
