- name: add Vault secrets
  include_vars: "{{ playbook_dir }}/secrets.yml"
  tags: always

- import_tasks: users.yml
  tags: users

- import_tasks: raspi-config.yml
  tags: raspi-config

- import_tasks: avahi.yml
  tags: avahi
  vars:
    aliases:
      - homebridge.local

- name: configure wpa_supplicant
  tags: wifi
  become: yes
  template:
    src: ./templates/wpa_supplicant.conf
    dest: /etc/wpa_supplicant/wpa_supplicant.conf
    owner: root
    group: root
    mode: 0644
  notify: wifi-reconnect

- name: install useful utils
  become: yes
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: no
  vars:
    packages:
      - htop
      - bind9-dnsutils

- name: set up bash aliases
  template:
    src: ./templates/.bash_aliases
    dest: /home/{{ ansible_ssh_user }}/.bash_aliases
    mode: 0644
