# borrowed pieces from https://github.com/glennklockwood/rpi-ansible/blob/master/roles/rpi/tasks/raspi-facts.yml

- name: get hostname
  command: "raspi-config nonint get_hostname"
  register: current_hostname
  changed_when: False

- name: get GPU memory split
  command: "raspi-config nonint get_config_var gpu_mem /boot/config.txt"
  register: raspi_gpu_mem
  changed_when: no
  check_mode: no

- name: set raspi-config facts (all)
  set_fact:
    current_hostname: "{{ current_hostname.stdout }}"
    raspi_gpu_mem: "{{ raspi_gpu_mem.stdout }}"
  check_mode: no

- name: "set hostname"
  hostname:
    name: "pi"
  when: current_hostname != 'pi'
  notify:
    - reboot

- name: set GPU memory split
  community.general.ini_file:
    path: /boot/config.txt
    section: all
    option: gpu_mem
    value: 1
    mode: 755
  when: raspi_gpu_mem != '1'
  notify:
    - reboot



