promtail:
  image:  grafana/promtail
  container_name: promtail
  volumes:
    - ./promtail/config.yml:/etc/promtail/config.yml
    - /var/lib/docker/containers:/var/lib/docker/containers:ro
    - /var/run/docker.sock:/var/run/docker.sock
    - /var/log:/mapped/var/log/:ro
  command: -config.file=/etc/promtail/config.yml
