# https://grafana.com/docs/loki/latest/clients/promtail/configuration/
# https://docs.docker.com/engine/api/v1.41/#operation/ContainerList
server:
  http_listen_port: 0
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: docker_scrape
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 30s
    relabel_configs:
      - source_labels: ['__meta_docker_container_name']
        regex: '/(.*)'
        target_label: 'container'
  - job_name: system
    static_configs:
    - targets:
        - localhost
      labels:
        job: varlogs
        __path__: /mapped/var/log/*.log
        __path_exclude__: /mapped/var/log/daemon.log
  - job_name: systemd-journal
    pipeline_stages:
      - drop:
          source: systemd_unit
          expression: session-\d+\.scope
      - drop:
          source: systemd_unit
          expression: user@\d+\.service
      - drop:
          source: systemd_unit
          expression: init.scope
    journal:
      path: /mapped/var/log/journal
      labels:
        job: systemd-journal
    relabel_configs:
      - source_labels: ['__journal__systemd_unit']
        target_label: 'systemd_unit'
