---

- name: Download dops executable and place it in PATH
  become: true
  ansible.builtin.get_url:
    url: https://github.com/Mikescher/better-docker-ps/releases/download/v1.7/dops_linux-amd64-static
    dest: /usr/local/bin/dops
    mode: "755"

- name: Route 'docker ps' calls to dops with .bashrc function
  ansible.builtin.blockinfile:
    dest: /home/{{ ansible_ssh_user }}/.bashrc
    marker: "# {mark} dops"
    content: |
      docker() {
        case $1 in
          ps)
            shift
            command dops "$@"
            ;;
          *)
            command docker "$@";;
        esac
      }
