- name: stat apt lists
  stat:
    path: /var/lib/apt/lists/partial
  register: stat_results

- name: update apt cache
  become: yes
  apt:
    update_cache: yes
  when: ((ansible_date_time.epoch|int - stat_results.stat.mtime) > (60 * 60 * 24 * 7)) # not updated in last week

- name: install docker and docker-compose
  become: yes
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - docker.io=20.10.5+dfsg1-1+deb11u1
      - docker-compose=1.25.0-1

- name: add existing user '{{ ansible_facts['user_id'] }}' to docker group
  user:
    name: "{{ ansible_facts['user_id'] }}"
    groups: docker
    append: yes

- name: make sure docker service is running and enable it on reboot
  become: yes
  systemd:
    state: started
    enabled: yes
    name: docker
