- name: install deps for docker installation and orchestration
  become: true
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - ca-certificates
      - gpg
      - python3
      - python3-pip

- name: get arch from dpkg
  command: dpkg --print-architecture
  register: dpkg_arch
  changed_when: no

- name: download docker signing gpg key
  become: true
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    keyring: /usr/share/keyrings/docker-archive-keyring.gpg

- name: add the docker sources.list
  become: true
  apt_repository:
    filename: /etc/apt/sources.list.d/docker
    repo: deb [arch={{ dpkg_arch.stdout }} signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/debian {{ ansible_facts['lsb'].codename }} stable
    update_cache: yes

- name: install docker-ce
  become: true
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - docker-ce

- name: add existing user '{{ main_user }}' to docker group
  become: true
  user:
    name: "{{ main_user }}"
    groups: docker
    append: yes
  notify: logout

- name: make sure docker service is running and enable it on reboot
  become: true
  systemd:
    state: started
    enabled: yes
    name: docker

- name: install Python library for Docker so Ansible can orchestrate it
  pip:
    name: docker
    version: ">=5.0.0"
    state: present
