---
- name: Gather facts
  setup:

- name: Install deps for docker installation and orchestration
  become: true
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - ca-certificates
      - gpg
      - python3
      - python3-pip

- name: Get arch from dpkg
  command: dpkg --print-architecture
  register: dpkg_arch
  changed_when: false

- name: Add the docker sources.list
  become: true
  ansible.builtin.deb822_repository:
    name: docker
    types: deb
    uris: https://download.docker.com/linux/debian
    suites: "{{ ansible_facts['lsb'].codename }}"
    components: stable
    architectures: "{{ dpkg_arch.stdout }}"
    signed_by: https://download.docker.com/linux/debian/gpg

- name: Install docker-ce
  become: true
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - docker-ce
      - python3-docker

- name: "Add existing user to docker group: {{ ansible_ssh_user }}"
  become: true
  user:
    name: "{{ ansible_ssh_user }}"
    groups: docker
    append: true
  notify: Logout

- name: Make sure docker service is running and enable it on reboot
  become: true
  systemd:
    state: started
    enabled: true
    name: docker

- name: Improve the formatting of 'docker ps'
  import_tasks: dops.yml
