---
- name: Install avahi dependencies
  become: true
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - make
      - unzip
      - avahi-daemon

- name: Download avahi-aliases
  become: true
  unarchive:
    remote_src: true
    src: https://github.com/scott-ainsworth/avahi-aliases/archive/refs/heads/main.zip
    dest: /usr/local/src/
    creates: /usr/local/src/avahi-aliases-main

- name: Make /etc/avahi a directory
  become: true
  file:
    path: /etc/avahi
    state: directory
    mode: "755"

- name: Install avahi-aliases scripts
  become: true
  command:
    chdir: /usr/local/src/avahi-aliases-main
    cmd: make install
    creates: /usr/local/bin/avahi-add-alias
  register: command_result
  failed_when: "'Started Avahi Aliases' not in command_result.stdout and 'skipped' not in command_result.stdout"

- name: Start/enable avahi-aliases service
  become: true
  systemd:
    state: started
    enabled: true
    name: avahi-alias

- name: Get desired avahi aliases from services definition
  ansible.builtin.set_fact:
    desired_aliases: "{{ compose_services | selectattr('avahi', 'true') | map(attribute='name') | map('regex_replace', '$', '.' + local_domain) }}"

- name: "Set a top-level .local Avahi hostname for local domain"
  ansible.builtin.set_fact:
    desired_aliases: "{{ desired_aliases + [local_domain] }}"

- name: Configure /etc/avahi/aliases
  become: true
  template:
    src: ./templates/avahi-aliases.j2
    dest: "/etc/avahi/aliases"
    mode: "0644"
  diff: true

