---
- name: Install avahi dependencies
  become: true
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - make
      - unzip
      - avahi-daemon

- name: Download avahi-aliases
  become: true
  unarchive:
    remote_src: true
    src: https://github.com/scott-ainsworth/avahi-aliases/archive/refs/heads/main.zip
    dest: /usr/local/src/
    creates: /usr/local/src/avahi-aliases-main

- name: Make /etc/avahi a directory
  become: true
  file:
    path: /etc/avahi
    state: directory
    mode: "755"

- name: Install avahi-aliases scripts
  become: true
  command:
    chdir: /usr/local/src/avahi-aliases-main
    cmd: make install
    creates: /usr/local/bin/avahi-add-alias
  register: command_result
  failed_when: "'Started Avahi Aliases' not in command_result.stdout and 'skipped' not in command_result.stdout"

- name: Start/enable avahi-aliases service
  become: true
  systemd:
    state: started
    enabled: true
    name: avahi-alias

- name: Get desired avahi aliases from services definition
  ansible.builtin.set_fact:
    desired_aliases: "{{ services | selectattr('http', 'defined') | map(attribute='name') | map('regex_replace', '$', '.local') }}"

- name: "Additionally set a top-level .local Avahi hostname for the box: {{ inventory_hostname }}"
  ansible.builtin.set_fact:
    desired_aliases: "{{ desired_aliases + [inventory_hostname + '.local'] }}"

- name: Get existing avahi aliases
  slurp:
    src: /etc/avahi/aliases
  register: slurped

- name: Set avahi aliases as facts
  ansible.builtin.set_fact:
    aliasfile_content: "{{ slurped['content'] | b64decode | trim }}"

- name: Split avahi aliases to array
  ansible.builtin.set_fact:
    cacheable: true
    existing_aliases: "{{ aliasfile_content.split('\n') }}"

- name: Create avahi aliases for all services
  become: true
  command:
    cmd: avahi-add-alias {{ item }}
  loop: "{{ desired_aliases | difference(existing_aliases) }}"
  when: desired_aliases | difference(existing_aliases) | length
  register: add_alias
  failed_when: add_alias.stderr
  changed_when: "'added' in add_alias.stdout"

- name: Remove undesired avahi aliases
  become: true
  command:
    cmd: avahi-remove-alias {{ item }}
  loop: "{{ existing_aliases | difference(desired_aliases) }}"
  when: existing_aliases | difference(desired_aliases) | length
