- name: install unzip utils
  become: yes
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - make
      - unzip

- name: download avahi-aliases
  become: yes
  unarchive:
    remote_src: yes
    src: https://github.com/scott-ainsworth/avahi-aliases/archive/refs/heads/main.zip
    dest: /usr/local/src/
    creates: /usr/local/src/avahi-aliases-main

- name: make /etc/avahi a directory
  become: yes
  file:
    path: /etc/avahi
    state: directory

- name: install avahi-aliases scripts
  become: yes
  command:
    chdir: /usr/local/src/avahi-aliases-main
    cmd: make install
    creates: /usr/local/bin/avahi-add-alias
  register: command_result
  failed_when: "'Started Avahi Aliases' not in command_result.stdout and 'skipped' not in command_result.stdout"

- name: start/enable avahi-aliases service
  become: yes
  systemd:
    state: started
    enabled: yes
    name: avahi-alias

- name: get existing avahi aliases
  slurp:
    src: /etc/avahi/aliases
  register: slurped

- name: set avahi aliases as facts
  set_fact:
    aliasfile_content: "{{ slurped['content'] | b64decode | trim }}"

- name: split avahi aliases to array
  set_fact:
    cacheable: yes
    avahi_aliases: "{{ aliasfile_content.split('\n') }}"

- name: create avahi aliases for all services
  become: yes
  command:
    cmd: avahi-add-alias {{ item }}
  loop: "{{ aliases | difference(ansible_facts['avahi_aliases']) }}"
  when: aliases | difference(ansible_facts['avahi_aliases']) | length
  register: add_alias
  failed_when: add_alias.stderr
  changed_when: "'added' in add_alias.stdout"

- name: remove undesired avahi aliases
  become: yes
  command:
    cmd: avahi-remove-alias {{ item }}
  loop: "{{ ansible_facts['avahi_aliases'] | difference(aliases) }}"
  when: ansible_facts['avahi_aliases'] | difference(aliases) | length
