---

- name: Install Bluetooth dependencies
  become: true
  ansible.builtin.apt:
    package: "{{ item }}"
    state: present
  loop:
    - bluetooth
    - bluez

- name: Enable bluetooth service
  become: true
  service:
    name: bluetooth
    enabled: true
    state: started

# Instructions on connecting a device using `bluetooth-agent` here:
# https://wiki.debian.org/BluetoothUser#Pairing%20using%20CLI
