- name: edit sshd_config to disable password auth
  become: true
  lineinfile:
    path: /etc/ssh/sshd_config
    regex: ^(# *)?PasswordAuthentication
    line: PasswordAuthentication no
  notify:
    - restart-ssh-service

# @TODO: This breaks the second-run experience because we can't gather facts using the first_run username anymore
# This may not be possible while remaining idempotent and being able to run on out-of-the-box server
# - name: remove unused users
#   become: true
#   user:
#     name: "{{item}}"
#     state: absent
#     remove: true
#     force: true
#   loop:
#     - debian
#     - vagrant

# @TODO: update AllowedGroups to only permit our user to SSH
# Same issue here this is probably going to break Vagrant
# https://github.com/imthenachoman/How-To-Secure-A-Linux-Server#secure-etcsshsshd_config

# @TODO: enable UFW
# https://github.com/imthenachoman/How-To-Secure-A-Linux-Server#firewall-with-ufw-uncomplicated-firewall

# @TODO: set up clamav?
# https://github.com/imthenachoman/How-To-Secure-A-Linux-Server#anti-virus-scanning-with-clamav-wip
