---
- name: Edit sshd_config to disable password auth
  become: true
  lineinfile:
    path: /etc/ssh/sshd_config
    regex: ^(# *)?PasswordAuthentication
    line: PasswordAuthentication no
  notify:
    - Restart ssh service

- name: Remove unused users
  become: true
  user:
    name: "{{ item }}"
    state: absent
    remove: true
    force: true
  loop:
    - debian
    - vagrant

- name: Create sshers group
  become: true
  group:
    name: sshers
    state: present

- name: "Put user in sshers group: {{ ansible_ssh_user }}"
  become: true
  user:
    name: "{{ ansible_ssh_user }}"
    groups: sshers
    append: true

- name: Configure ssh so that only sshers can ssh
  become: true
  lineinfile:
    path: /etc/ssh/sshd_config
    regex: ^(# *)?AllowGroups
    line: AllowGroups sshers
  notify:
    - Restart ssh service

- name: Install fail2ban
  become: true
  apt:
    name: fail2ban
    state: present

- name: Template fail2ban config
  become: true
  template:
    src: ./templates/fail2ban/fail2ban.local
    dest: /etc/fail2ban/fail2ban.local
    mode: "0644"
  notify:
    - Restart fail2ban service

- name: Template fail2ban jail config
  become: true
  template:
    src: ./templates/fail2ban/jail.local
    dest: /etc/fail2ban/jail.local
    mode: "0644"
  notify:
    - Restart fail2ban service

# @TODO: enable UFW
# https://github.com/imthenachoman/How-To-Secure-A-Linux-Server#firewall-with-ufw-uncomplicated-firewall

# @TODO: set up clamav?
# https://github.com/imthenachoman/How-To-Secure-A-Linux-Server#anti-virus-scanning-with-clamav-wip
