- name: edit sshd_config to disable password auth
  become: yes
  lineinfile:
    path: /etc/ssh/sshd_config
    regex: ^(# *)?PasswordAuthentication
    line: PasswordAuthentication no
  notify:
    - restart-ssh-service
