---
- name: List everything in apt_cache
  become: true
  command: apt-cache pkgnames
  register: apt_pkgs
  changed_when: false

- name: Determine if apt update has never run (netinst)
  ansible.builtin.set_fact:
    netinst: apt_pkgs|length < 1000

- name: Run initial populate of apt cache (if empty due to netinst)
  become: true
  apt:
    update_cache: true
  when: netinst

- name: Do security setup
  import_tasks: lockdown.yml

- name: Configure avahi and daemon for .local hostnames
  import_tasks: avahi.yml

- name: Setup WiFi
  import_tasks: wifi.yml
  when: "'wlan0' in ansible_interfaces"

- name: Set hostname
  become: true
  hostname:
    name: "{{ inventory_hostname }}"
  notify:
    - Reboot

- name: Install useful utils
  become: true
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - htop
      - bind9-dnsutils

- name: Set up bash aliases
  ansible.builtin.template:
    src: ./templates/.bash_aliases
    dest: /home/{{ ansible_ssh_user }}/.bash_aliases
    mode: "0644"

- name: Enable memory cgroup in grub
  become: true
  lineinfile:
    state: present
    path: /etc/default/grub
    line: GRUB_CMDLINE_LINUX="cgroup_enable=memory"
    backup: true
  notify:
    - Update grub
    - Reboot
