---
- name: Gather facts
  setup:

- name: Configure and populate apt sources
  import_tasks: apt.yml

- name: Do security setup
  import_tasks: lockdown.yml

- name: Configure avahi and daemon for .local hostnames
  import_tasks: avahi.yml

- name: Setup mosh as replacement ssh
  import_tasks: mosh.yml

- name: Set hostname
  become: true
  hostname:
    name: "{{ inventory_hostname }}"
  notify:
    - Reboot

- name: Update hosts file with new hostname
  become: true
  ansible.builtin.lineinfile:
    path: /etc/hosts
    search_string: "127.0.1.1"
    line: "127.0.1.1 {{ inventory_hostname }}"
  notify:
    - Reboot

- name: Set up bash aliases
  ansible.builtin.template:
    src: ./templates/.bash_aliases
    dest: /home/{{ ansible_ssh_user }}/.bash_aliases
    mode: "0644"
