- name: check if connection using {{ main_user }} and pubkey auth is possible
  command: ssh -o User={{ main_user }} -o ConnectTimeout=10 -o PreferredAuthentications=publickey -o PubkeyAuthentication=yes -o StrictHostKeyChecking=no {{ansible_ssh_host}} -p {{ansible_ssh_port}} echo "Worked"
  register: correct_key_auth
  connection: local
  ignore_errors: true
  changed_when: False

- import_tasks: first_run.yml
  when: correct_key_auth.failed

- name: list everything in apt_cache
  become: true
  command: apt-cache pkgnames
  register: apt_pkgs
  changed_when: False

- name: determine if apt update has never run (netinst)
  set_fact:
    netinst: apt_pkgs|length < 1000

- name: run initial populate of apt cache (if empty due to netinst)
  become: true
  apt:
    update_cache: yes
  when: netinst

- import_tasks: lockdown.yml

- import_tasks: avahi.yml
  vars:
    aliases:
      - homebridge.local
      - pihole.local
      - homelab.local
      - vmagent.local

- import_tasks: wifi.yml
  when: "'wlan0' in ansible_interfaces"

- name: set hostname
  become: true
  hostname:
    name: "{{ inventory_hostname }}"
  notify:
    - reboot

- name: install useful utils
  become: true
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - htop
      - bind9-dnsutils

- name: set up bash aliases
  template:
    src: ./templates/.bash_aliases
    dest: /home/{{ ansible_ssh_user }}/.bash_aliases
    mode: 0644

- name: enable memory cgroup in grub
  become: true
  lineinfile:
    state: present
    path: /etc/default/grub
    line: GRUB_CMDLINE_LINUX="cgroup_enable=memory"
    backup: true
  notify:
    - update grub
    - reboot
