- name: add Vault secrets
  include_vars: "{{ playbook_dir }}/secrets.yml"
  tags: always

- import_tasks: first_run.yml

- import_tasks: lockdown.yml

- import_tasks: avahi.yml
  vars:
    aliases:
      - homebridge.local
      - pihole.local
      - homelab.local
      - vmagent.local

- import_tasks: wifi.yml

- name: set hostname
  become: true
  hostname:
    name: "{{ inventory_hostname }}"
  notify:
    - reboot

- name: install useful utils
  become: yes
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - htop
      - bind9-dnsutils

- name: set up bash aliases
  template:
    src: ./templates/.bash_aliases
    dest: /home/{{ ansible_ssh_user }}/.bash_aliases
    mode: 0644

- name: enable memory cgroup in grub
  become: yes
  lineinfile:
    state: present
    path: /etc/default/grub
    line: GRUB_CMDLINE_LINUX="cgroup_enable=memory"
    backup: true
  notify:
    - update grub
    - reboot
