- name: store desired username for main account in facts
  set_fact:
    main_user: "{{ ansible_ssh_user }}"

- name: login using default credentials
  set_fact:
    ansible_ssh_user: pi
    ansible_ssh_pass: raspberry

- name: edit sshd_config to enable pubkey auth
  become: yes
  lineinfile:
    path: /etc/ssh/sshd_config
    regex: ^(# *)?PubkeyAuthentication
    line: PubkeyAuthentication yes
  notify:
    - restart-ssh-service

- name: flush handlers
  meta: flush_handlers

- name: create '{{ main_user }}' sudo user
  become: yes
  user:
    name: "{{ main_user }}"
    password: "{{ ansible_become_pass | string | password_hash('sha256', 'salt', rounds=1000) }}"
    append: yes
    shell: /bin/bash
    groups:
      - sudo
      - adm
      - dialout
      - cdrom
      - audio
      - video
      - plugdev
      - games
      - input
      - netdev
      - spi
      - i2c
      - gpio

- name: add the control node's ssh key to authorized_keys
  become: yes
  become_user: "{{ main_user }}"
  ansible.posix.authorized_key:
    user: "{{ main_user }}"
    key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
    state: present

- name: run future steps using "{{ main_user }}" user and pubkey auth
  set_fact:
    ansible_ssh_user: "{{ main_user  }}"
    ansible_ssh_pass:
