---
- name: Install wpa supplicant
  become: true
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - wpasupplicant

- name: Configure wpa_supplicant
  become: true
  ansible.builtin.template:
    src: ./templates/wpa_supplicant.conf
    dest: /etc/wpa_supplicant/wpa_supplicant.conf
    owner: root
    group: root
    mode: "0644"
  notify: Reconnect WiFi
