---
- name: Grep dmesg to determine if we need nonfree wifi firmware
  become: true
  ansible.builtin.shell:
    cmd: |
      set -o pipefail #
      dmesg -l err | grep "failed to load iwlwifi"
  register: intel_wifi_module_failed
  failed_when: false
  changed_when: false

- name: Install nonfree Intel wifi firmware
  become: true
  apt:
    name: firmware-iwlwifi
    state: present
  when: intel_wifi_module_failed.stdout

- name: Add nonfree Intel wifi kernel module
  become: true
  community.general.modprobe:
    name: iwlwifi
    state: present
  when: intel_wifi_module_failed.stdout
  notify: Reboot

- name: Flush handlers
  meta: flush_handlers

- name: Re-gather facts on network interfaces
  ansible.builtin.setup:
    gather_subset: interfaces

- name: Identify wireless interface (if exists)
  ansible.builtin.set_fact:
    wireless_interface: "{{ ansible_interfaces | select('match', 'wl*') | first | default(False) }}"

- name: Install nmcli
  become: true
  apt:
    package: network-manager
    state: present

- name: Add connection to IoT wifi using nmcli (NetworkManager)
  become: true
  community.general.nmcli:
    type: wifi
    conn_name: IOT WiFi Network
    ifname: "{{ wireless_interface }}"
    ssid: "brian iot ssid"
    wifi:
      hidden: true
    wifi_sec:
      key-mgmt: wpa-psk
      psk: "{{ wifi_psk }}"
    state: present
    autoconnect: false # Note: We used to autoconnect, but this interface has issues
  notify: Restart NetworkManager service
