vmagent:
  container_name: vmagent
  image: victoriametrics/vmagent
  expose:
    - "8429"
  volumes:
    - vmagent-data:/vmagentdata
    - ./vmagent/prometheus.yml:/etc/prometheus/prometheus.yml
  command:
    - "--promscrape.config=/etc/prometheus/prometheus.yml"
    - "--remoteWrite.url=http://prometheus:9090/api/prom/push"
    - "--opentsdbHTTPListenAddr=:4242"
