vmagent:
  container_name: vmagent
  image: victoriametrics/vmagent
  expose:
    - "8429"
    - "4242"
  ports:
    - 4242:4242
  volumes:
    - vmagent-data:/vmagentdata
    - ./vmagent/prometheus.yml:/etc/prometheus/prometheus.yml
  command:
    - "--promscrape.config=/etc/prometheus/prometheus.yml"
    - "--remoteWrite.url=http://prometheus:9090/api/v1/write"
    - "--remoteWrite.showURL"
    - "--opentsdbHTTPListenAddr=:4242"
