scrape_configs:
  - job_name: 'unifipoller'
    scrape_interval: 30s
    static_configs:
    - targets:
      - unifi-poller:9130
  - job_name: cadvisor
    scrape_interval: 30s
    static_configs:
    - targets:
      - cadvisor:8080
