---
- block:
  - name: Create configuration directory
    file:
      path: "{{ compose_project_dir }}/mqtt2prometheus"
      state: directory
      mode: "0755"

  - name: Add conf file
    template:
      src: ./templates/config.yaml
      dest: "{{ compose_project_dir }}/mqtt2prometheus/config.yaml"
      mode: "0644"
    notify: Restart mqtt2prometheus
  tags: mqtt2prometheus
