homebridge:
  container_name: homebridge
  image: oznu/homebridge:2023-01-08
  network_mode: host
  environment:
    - TZ=America/New_York
  volumes:
    - homebridge-data:/homebridge
  labels:
    - docker-volume-backup.stop-during-backup=true
  healthcheck:
    test: [ "CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:8581/api || exit 1" ]

