homebridge:
  container_name: homebridge
  image: oznu/homebridge:2023-01-08
  network_mode: host
  environment:
    - TZ=America/New_York
  volumes:
    - homebridge-data:/homebridge
    - ./homebridge/homebridge-config.json:/homebridge/config.json
    - ./homebridge/package.json:/homebridge/package.json
    - ./homebridge/development-plugins:/homebridge/development-plugins
  labels:
    - docker-volume-backup.stop-during-backup=true
