trackr:
  image: ghcr.io/bjacobel/trackr:master
  container_name: trackr
  expose:
    - "3000"
  environment:
    - OPENTSDB_HOST=vmagent
    - OPENTSDB_PORT=4242
    - NEXT_PUBLIC_TRACKD_RELATIVE="Ringing,Anxiety,Headaches,Jaw pain,Back pain"
