prometheus:
  image: prom/prometheus
  container_name: prometheus
  volumes:
    - prometheus-data:/prometheus
    - ./prometheus:/etc/prometheus
  expose:
    - "9090"
  environment:
    - TZ=America/New_York
  command:
    - "--web.enable-remote-write-receiver"
    - "--config.file=/etc/prometheus/prometheus.yml"
  labels:
    - docker-volume-backup.stop-during-backup=true
