prometheus:
  image: prom/prometheus
  container_name: prometheus
  volumes:
    - prometheus-data:/prometheus
    - ./prometheus:/etc/prometheus
  expose:
    - "9090"
  ports:
    - 9090:9090
  environment:
    - TZ=America/New_York
  command:
    - "--web.enable-remote-write-receiver"
    - "--web.enable-admin-api"
    - "--storage.tsdb.retention.size=50GB"
    - "--storage.tsdb.retention.time=5y"
    - "--config.file=/etc/prometheus/prometheus.yml"
  labels:
    - docker-volume-backup.stop-during-backup=true
  healthcheck:
    test: [ "CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:9090/-/healthy || exit 1" ]
