prometheus:
  image: prom/prometheus
  container_name: prometheus
  volumes:
    - prometheus-data:/prometheus
    - ./prometheus:/etc/prometheus
  expose:
    - "9090"
  environment:
    - TZ=America/New_York
