global:
  scrape_interval:     30s
  evaluation_interval: 30s

storage:
  tsdb:
    out_of_order_time_window: 365d

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
        - localhost:9090
  - job_name: unifipoller
    static_configs:
    - targets:
      - unifi-poller:9130
  - job_name: cadvisor
    static_configs:
    - targets:
      - cadvisor:8080
  - job_name: node-exporter
    static_configs:
    - targets:
      - node-exporter:9100
  - job_name: pihole-exporter
    static_configs:
      - targets:
        - pihole-exporter:9617
