global:
  scrape_interval:     30s
  evaluation_interval: 30s

storage:
  tsdb:
    out_of_order_time_window: 5y

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
        - localhost:9090
  - job_name: unifipoller
    static_configs:
      - targets:
        - unifi-poller:9130
  - job_name: cadvisor
    static_configs:
      - targets:
        - cadvisor:8080
  - job_name: node-exporter
    static_configs:
      - targets:
        - node-exporter:9100
  - job_name: pihole-exporter
    static_configs:
      - targets:
        - pihole-exporter:9617
  - job_name: ntfy
    static_configs:
      - targets:
        - ntfy:9090
  - job_name: node-red
    static_configs:
      - targets:
        - node-red:1880
  - job_name: docker-state-exporter
    static_configs:
      - targets:
        - docker-state-exporter:8080
