---
- name: Bring Wireguard up
  community.docker.docker_compose:
    project_src: "{{ compose_project_dir }}"
    services: wireguard
    state: present

- name: Find the location of the Wireguard config dir
  command:
    cmd: docker volume inspect wireguard-data
  register: wireguard_volume_inspect
  changed_when: false

- name: Set Wireguard data location in facts
  set_fact:
    wireguard_config_dir: "{{ wireguard_volume_inspect.stdout | from_json | json_query('[0].Mountpoint') }}"

- name: Copy specific config file to control node
  become: true
  ansible.builtin.fetch:
    src: "{{ wireguard_config_dir }}/peer_calus/peer_calus.conf"
    dest: ~/Wireguard/
    flat: true

- name: Copy specific config file to control node (for my phone)
  become: true
  ansible.builtin.fetch:
    src: "{{ wireguard_config_dir }}/peer_clovis/peer_clovis.png"
    dest: ~/Wireguard/
    flat: true
