node-exporter:
  container_name: node-exporter
  image: prom/node-exporter
  user: root
  volumes:
    - /proc:/host/proc:ro,rslave
    - /sys:/host/sys:ro,rslave
    - /:/rootfs:ro,rslave
  command:
    - '--path.procfs=/host/proc'
    - '--path.rootfs=/rootfs'
    - '--path.sysfs=/host/sys'
    - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
  expose:
    - 9100
